# Generated by Django 5.2 on 2025-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('idbox', models.AutoField(db_column='idBox', primary_key=True, serialize=False)),
                ('numerobox', models.IntegerField(blank=True, db_column='numeroBox', null=True)),
                ('especialidadbox', models.CharField(blank=True, db_column='especialidadBox', max_length=100, null=True)),
            ],
            options={
                'db_table': 'box',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Boximplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'boximplemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idconsulta', models.AutoField(db_column='idConsulta', primary_key=True, serialize=False)),
                ('fechaconsulta', models.DateField(blank=True, db_column='fechaConsulta', null=True)),
                ('horainicio', models.TimeField(blank=True, db_column='horaInicio', null=True)),
                ('horafin', models.TimeField(blank=True, db_column='horaFin', null=True)),
            ],
            options={
                'db_table': 'consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('idespecialidad', models.AutoField(db_column='idEspecialidad', primary_key=True, serialize=False)),
                ('nombreespecialidad', models.CharField(db_column='nombreEspecialidad', max_length=20)),
            ],
            options={
                'db_table': 'especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idestado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('descripcionestado', models.TextField(blank=True, db_column='descripcionEstado', null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadobox',
            fields=[
                ('idestadobox', models.AutoField(db_column='idEstadoBox', primary_key=True, serialize=False)),
                ('descripcionestadobox', models.TextField(blank=True, db_column='descripcionEstadoBox', null=True)),
            ],
            options={
                'db_table': 'estadobox',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadoimplemento',
            fields=[
                ('idestadoimplemento', models.AutoField(db_column='idEstadoImplemento', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estadoimplemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Implemento',
            fields=[
                ('idimplemento', models.AutoField(db_column='idImplemento', primary_key=True, serialize=False)),
                ('nombreimplemento', models.CharField(blank=True, db_column='nombreImplemento', max_length=60, null=True)),
            ],
            options={
                'db_table': 'implemento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rutmedico', models.CharField(db_column='rutMedico', max_length=11, primary_key=True, serialize=False)),
                ('nombremedico', models.CharField(blank=True, db_column='nombreMedico', max_length=60, null=True)),
                ('apellidomedico', models.CharField(blank=True, db_column='apellidoMedico', max_length=60, null=True)),
                ('fechanacimientomedico', models.DateField(blank=True, db_column='fechaNacimientoMedico', null=True)),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('rutpaciente', models.CharField(db_column='rutPaciente', max_length=11, primary_key=True, serialize=False)),
                ('nombrepaciente', models.CharField(blank=True, db_column='nombrePaciente', max_length=60, null=True)),
                ('apellidopaciente', models.CharField(blank=True, db_column='apellidoPaciente', max_length=60, null=True)),
                ('fechanacimientopaciente', models.DateField(blank=True, db_column='fechaNacimientoPaciente', null=True)),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('idpasillo', models.AutoField(db_column='idPasillo', primary_key=True, serialize=False)),
                ('nombrePasillo', models.CharField(blank=True, db_column='pasillo', max_length=60, null=True)),
            ],
            options={
                'db_table': 'pasillo',
                'managed': True,
            },
        ),
    ]
